# Generated by Django 3.0.5 on 2020-04-27 22:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=10)),
                ('unit', models.CharField(max_length=10)),
                ('image_1', models.ImageField(blank=True, upload_to='requisition/%Y/%m/%d/')),
                ('image_2', models.ImageField(blank=True, upload_to='requisition/%Y/%m/%d/')),
                ('image_3', models.ImageField(blank=True, upload_to='requisition/%Y/%m/%d/')),
                ('image_4', models.ImageField(blank=True, upload_to='requisition/%Y/%m/%d/')),
                ('image_5', models.ImageField(blank=True, upload_to='requisition/%Y/%m/%d/')),
                ('image_6', models.ImageField(blank=True, upload_to='requisition/%Y/%m/%d/')),
                ('status', models.IntegerField(choices=[(1, 'Not Published'), (2, 'Pending'), (3, 'Authorized'), (4, 'Approved'), (5, 'Procured'), (6, 'Dispatched'), (7, 'Delivered'), (8, 'Recieved')])),
                ('due_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Approver', to='employee.Employee')),
                ('authorizer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Authorizer', to='employee.Employee')),
                ('originator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Originator', to='employee.Employee')),
            ],
        ),
    ]
