# Generated by Django 3.0.5 on 2020-04-27 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('requisition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approver', to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='authorizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='authorizer', to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='originator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='originator', to='employee.Employee'),
        ),
    ]
